Repository canonical/mysql-router-k8s-operator, pull requests merged in 2025-02, with the labels that each got.

#396 [DPE-6653] Signal outdated charm libs with a label
  .github/workflows/charm_libs.yaml
  .github/workflows/ci.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#397 feat: dpe-6306 Static code analysis
  .github/actionlint.yaml
  .github/workflows/tiobe_scan.yaml
Labels: not bug or enhancement, Libraries: Out of sync

#330 Consolidate all COS objects in one location
  src/abstract_charm.py
  src/relations/cos.py
Labels: Libraries: Out of sync

#399 [DPE-6651] Update rock tag for new builds with updated percona packages
  metadata.yaml
Labels: enhancement, Libraries: Out of sync

#400 [DPE-6652] Refresh all charm libs
  lib/charms/data_platform_libs/v0/data_interfaces.py
  lib/charms/grafana_k8s/v0/grafana_dashboard.py
  lib/charms/loki_k8s/v1/loki_push_api.py
  lib/charms/prometheus_k8s/v0/prometheus_scrape.py
  lib/charms/tempo_coordinator_k8s/v0/tracing.py
  lib/charms/tls_certificates_interface/v2/tls_certificates.py
  poetry.lock
  pyproject.toml
Labels: not bug or enhancement, Libraries: Out of sync
